### PR TITLE
Basic models raptor

### PR DESCRIPTION
**Pull request by jargonautNadeau**
Updated the Playground to be more basic with just water and land to move around.
Added the Raptor model to the project but it is without animations and the like.

### CODE REVIEW

**Comment by beccannlittle** [comment]
@jargonautNadeau It looks like the `Main Camera` is positioned incorrectly. Check out the Game view when you go into Play mode. Also, could you help me understand what the `Water4SimpleReflectionSceneCamera` is for? After I moved the camera up, something called `Water4SimpleReflectionMain Camera` was instantiated in the scene

**Comment by beccannlittle** [comment]
@jargonautNadeau also, use the method described in [this article](https://github.com/blog/1506-closing-issues-via-pull-requests) to edit your pull request so that it will close #3 when its merged.

**Comment by beccannlittle** [comment]
Testing. this branch closes #3

**Comment by jargonautNadeau** [comment]
All Up Dated!

**Pull request merged**
